# Generated by Django 3.0.14 on 2023-12-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20231223_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch_name',
            field=models.CharField(choices=[('Baner', 'Baner'), ('Katraj', 'Katraj'), ('Pimpari', 'Pimpari'), ('Bavdhan', 'Bavdhan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5, null=True),
        ),
    ]
